import 'package:json_annotation/json_annotation.dart';

// Note: Run 'flutter pub run build_runner build' to generate health_insight.g.dart
part 'health_insight.g.dart';

@JsonSerializable()
class HealthInsight {
  final String id;
  final DateTime timestamp;
  final String category;
  final String title;
  final String description;
  final Map<String, dynamic>? metrics;
  final List<String>? recommendations;
  final int? severity; // 0-100, where 0 is informational and 100 is critical

  HealthInsight({
    required this.id,
    required this.timestamp,
    required this.category,
    required this.title,
    required this.description,
    this.metrics,
    this.recommendations,
    this.severity,
  });

  // These methods will be generated by build_runner
  factory HealthInsight.fromJson(Map<String, dynamic> json) => _$HealthInsightFromJson(json);
  Map<String, dynamic> toJson() => _$HealthInsightToJson(this);
} 